name: flutter_github_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1
  flutter: '>=3.24.1'

dependencies:
  auto_route: ^9.2.2
  collection: ^1.18.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  hooks_riverpod: ^2.5.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.3.0
  riverpod_annotation: 2.3.5

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  graphql_codegen: ^1.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^9.0.0
  riverpod_generator: ^2.4.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
